# Site settings
title: Compufiber
email: consultas@compufiber.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.compufiber.com.py" # the base hostname & protocol for your site
facebook: https://www.facebook.com/profile.php?id=100004236797951
